CREATE SCHEMA IF NOT EXISTS soccerq;

DROP TYPE IF EXISTS soccerq.position;

CREATE TYPE soccerq.position AS ENUM (
    'GOAL KEEPER',
    'FORWARD',
    'DEFENDER'
);

DROP TYPE IF EXISTS soccerq.player_status;

CREATE TYPE soccerq.player_status AS ENUM (
    'AVAILABLE',
    'SOLD',
    'UNSOLD'
);

CREATE TYPE soccerq.team AS ENUM (
    'TEAM 1',
    'TEAM 2',
    'TEAM 3'
);

CREATE TABLE IF NOT EXISTS soccerq.player (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name CHARACTER VARYING(50)  NOT NULL,
    position soccerq.position NOT NULL,
    base_price INTEGER NOT NULL,
    sold_price INTEGER NOT NULL DEFAULT 0,
    status soccerq.player_status NOT NULL DEFAULT 'AVAILABLE',
    CONSTRAINT player_pkey PRIMARY KEY (id),
    CONSTRAINT player_ukey UNIQUE (name)
) WITHOUT OIDS;

CREATE TABLE IF NOT EXISTS soccerq.team_players (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    team soccerq.team NOT NULL,
    player_id INTEGER NOT NULL,
    CONSTRAINT tp_pkey PRIMARY KEY (id),
    CONSTRAINT tp_ukey UNIQUE (player_id)
) WITHOUT OIDS;